openapi: 3.0.0
info:
  title: Sample order API
  description: Простой обмен заявками и их статусами [Описание](https://api.test.com/help/).
  version: 0.0.1
servers:
  - url: https://api.test.com/v1
    description: Main (production) server
paths:
  /order.list:
    get:
      summary: Returns a list of orders.
      description: in list returned orders with status=0.
      responses:
        '200':    # status code
          description: A JSON array of orders
          content:
            application/json:
              schema: 
                type: "array"
                items: 
                  $ref: "#/components/schemas/Order"
  /status.set:
    post:
      summary: Set statuses of orders.
      description: send HTTP status code 200 in any situations
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: "array"
              items:
                $ref: "#/components/schemas/SetStatusObj"
      responses:
        '200':    # status code
          description: "all ok"
          content:
            application/json:
              schema: 
                type: "string"
components:
  schemas:
    Order:
      type: "object"
      properties:
        id:
          type: "integer"
          description: "id of order"
        status:
          $ref: "#/components/schemas/Statuses"
        memo:
          type: "string"
        shipDate:
          type: "string"
          format: "date-time"
        complete:
          type: "boolean"
          default: false
    SetStatusObj:
      type: "object"
      properties:
        id:
          type: "integer"
          description: "id of order"
        status:
          $ref: "#/components/schemas/Statuses"
        memo:
          type: "string"
    Statuses:
      type: "integer"
      description: "0 - ожидает отправки; 1 - черновик; 2 - В БАНКЕ; 13 - ЗАЯВКА НЕ НАЙДЕНА; 14 - ЗАВЕРШЕНА; 16 - В АРХИВЕ"
      enum:
      - 0
      - 1
      - 2
      - 13
      - 14
      - 16
  securitySchemes:
    BasicAuth:
      type: "http"
      scheme: "basic"
security:
  - BasicAuth: []
